ALTER TABLE schedules DROP COLUMN IF EXISTS 
  one , DROP COLUMN IF EXISTS
    two ,DROP COLUMN IF EXISTS
    three ,DROP COLUMN IF EXISTS
    four ,DROP COLUMN IF EXISTS
    five ,DROP COLUMN IF EXISTS
    six ,DROP COLUMN IF EXISTS
    seven ,DROP COLUMN IF EXISTS
    eight ,DROP COLUMN IF EXISTS
    nine ,DROP COLUMN IF EXISTS
    ten ,DROP COLUMN IF EXISTS
    eleven ,DROP COLUMN IF EXISTS
    twelve ,DROP COLUMN IF EXISTS
    thirteen ,DROP COLUMN IF EXISTS
    fourteen ,DROP COLUMN IF EXISTS
    fifteen ,DROP COLUMN IF EXISTS
    sixteen ,DROP COLUMN IF EXISTS
    seventeen ,DROP COLUMN IF EXISTS
    eighteen ,DROP COLUMN IF EXISTS
    nineteen ,DROP COLUMN IF EXISTS
    twenty ,DROP COLUMN IF EXISTS
    twentyone ,DROP COLUMN IF EXISTS
    twentytwo ,DROP COLUMN IF EXISTS
    twentythree ,DROP COLUMN IF EXISTS
    twentyfour;

