ALTER TABLE schedules
  ADD COLUMN
    one BOOLEAN DEFAULT FALSE NOT NULL,ADD COLUMN
    two BOOLEAN DEFAULT FALSE NOT NULL,ADD COLUMN
    three BOOLEAN DEFAULT FALSE NOT NULL,ADD COLUMN
    four BOOLEAN DEFAULT FALSE NOT NULL,ADD COLUMN
    five BOOLEAN DEFAULT FALSE NOT NULL,ADD COLUMN
    six BOOLEAN DEFAULT FALSE NOT NULL,ADD COLUMN
    seven BOOLEAN DEFAULT FALSE NOT NULL,ADD COLUMN
    eight BOOLEAN DEFAULT FALSE NOT NULL,ADD COLUMN
    nine BOOLEAN DEFAULT FALSE NOT NULL,ADD COLUMN
    ten BOOLEAN DEFAULT FALSE NOT NULL,ADD COLUMN
    eleven BOOLEAN DEFAULT FALSE NOT NULL,ADD COLUMN
    twelve BOOLEAN DEFAULT FALSE NOT NULL,ADD COLUMN
    thirteen BOOLEAN DEFAULT FALSE NOT NULL,ADD COLUMN
    fourteen BOOLEAN DEFAULT FALSE NOT NULL,ADD COLUMN
    fifteen BOOLEAN DEFAULT FALSE NOT NULL,ADD COLUMN
    sixteen BOOLEAN DEFAULT FALSE NOT NULL,ADD COLUMN
    seventeen BOOLEAN DEFAULT FALSE NOT NULL,ADD COLUMN
    eighteen BOOLEAN DEFAULT FALSE NOT NULL,ADD COLUMN
    nineteen BOOLEAN DEFAULT FALSE NOT NULL,ADD COLUMN
    twenty BOOLEAN DEFAULT FALSE NOT NULL,ADD COLUMN
    twentyone BOOLEAN DEFAULT FALSE NOT NULL,ADD COLUMN
    twentytwo BOOLEAN DEFAULT FALSE NOT NULL,ADD COLUMN
    twentythree BOOLEAN DEFAULT FALSE NOT NULL,ADD COLUMN
    twentyfour BOOLEAN DEFAULT FALSE NOT NULL;